language: node_js
node_js:
  - "14.15.5"

install:
  - npm install newman

before_script:
  - node --version
  - npm --version
  - node_modules/.bin/newman --version

script:
  - node_modules/.bin/newman run bitcoinz.postman_collection.json -e bitcoinz.postman_environment.json
